name: CI
on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: write
    pull-requests: write

jobs:
    test:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v4

            - name: setup pnpm
              uses: pnpm/action-setup@v4

            - name: setup node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm

            - name: install dependencies
              run: pnpm install

            - name: build
              run: pnpm build:prod

            - name: test
              run: pnpm test
    checks:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v3

            - name: setup pnpm
              uses: pnpm/action-setup@v4

            - name: setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: pnpm

            - name: install dependencies
              run: pnpm install

            - name: types
              run: pnpm types:check

            - name: prettier
              run: pnpm prettier:check

            - name: eslint
              run: pnpm eslint:check
    website:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code repository
              uses: actions/checkout@v3

            - name: setup pnpm
              uses: pnpm/action-setup@v4

            - name: setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: pnpm

            - name: install dependencies
              run: pnpm install

            - name: packages build
              run: pnpm build:prod

            - name: website build
              run: pnpm website:build
