name: Test every pull request

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    strategy:
      matrix:
        node-version: [20] # testing against one node version should be enough here
        os: [ubuntu-latest]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8
      - run: pnpm install
      - run: pnpm -r test
