name: Build website

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - run: pnpm install
      - run: pnpm -C ./projects/website/  build
