name: Build and deploy website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - run: pnpm install
      - run: pnpm -C ./projects/website/  build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./projects/website/build
          cname: svelte-add.com
